package session

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"

	"lato/internal/persist"
)

// New creates a new session with a unique ID and initializes its timestamps and message list.
func New() *Session {
	now := time.Now()

	return &Session{
		ID:        uuid.NewString(),
		CreatedAt: now,
		UpdatedAt: now,
		Messages:  []Message{},
	}
}

// sessionIDPattern constrains in-file session identifiers to a safe,
// portable character set so they can never name a path outside the
// sessions directory. Existing IDs generated by Lato (UUIDs) and by
// older releases (hex with hyphens) already conform.
var sessionIDPattern = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)

// validSessionID reports whether id is safe to use as a session file
// name. It rejects empty IDs, path traversal, separators, drive
// letters, and any character outside the portable set.
func validSessionID(id string) bool {
	if id == "" || len(id) > 128 {
		return false
	}
	return sessionIDPattern.MatchString(id)
}

// Save persists the session to a JSON file in the .lato/sessions directory,
// updating the UpdatedAt timestamp. The write is atomic: a partial file
// is never left behind.
func (s *Session) Save() error {
	if !validSessionID(s.ID) {
		return fmt.Errorf("save session: invalid session id %q", s.ID)
	}
	s.UpdatedAt = time.Now()

	dir := filepath.Join(".", ".lato", "sessions")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}

	path := filepath.Join(dir, s.ID+".json")

	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}

	return persist.WriteFileAtomically(path, data, 0o600)
}

// AddMessage adds a new message to the session and updates the UpdatedAt timestamp.
func (s *Session) AddMessage(role, content string) {
	s.Messages = append(s.Messages, Message{
		Role:    role,
		Content: content,
		Time:    time.Now(),
	})

	s.UpdatedAt = time.Now()
}

// Load retrieves a session from a JSON file based on its ID,
// returning an error if the file does not exist or cannot be read.
//
// Malformed session data is handled conservatively:
//  1. A strictly valid JSON session loads normally.
//  2. A truncated session (the file was cut off mid-write) is repaired
//     by closing the open strings/objects/arrays. The original corrupted
//     bytes are preserved alongside as <id>.json.corrupt.bak, and the
//     recovered session is returned.
//  3. Anything else fails with a clear diagnostic and the file is left
//     untouched — Load never silently discards or overwrites user data.
func Load(id string) (*Session, error) {
	if !validSessionID(id) {
		return nil, fmt.Errorf("load session: invalid session id %q", id)
	}

	path := filepath.Join(".", ".lato", "sessions", id+".json")

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var s Session
	if err := json.Unmarshal(data, &s); err == nil {
		if s.ID == "" {
			s.ID = id
		}
		return &s, nil
	}

	// Strict parse failed: only attempt a well-defined truncation repair.
	if repaired, ok := repairTruncatedJSON(data); ok {
		var recovered Session
		if err := json.Unmarshal(repaired, &recovered); err == nil {
			if recovered.ID == "" {
				recovered.ID = id
			}
			// Preserve the original corrupted bytes for the user.
			backup := path + ".corrupt.bak"
			if writeErr := os.WriteFile(backup, data, 0o600); writeErr != nil {
				// A backup failure must not hide a successful recovery.
				return &recovered, nil
			}
			return &recovered, nil
		}
	}

	return nil, fmt.Errorf("session file %s is corrupted and could not be recovered; the file was left unchanged: %v", path, "invalid JSON")
}

// repairTruncatedJSON closes a JSON document that was cut off before it
// finished: it strips a dangling comma/colon, closes an open string, and
// appends the closers for unbalanced braces/brackets. It returns the
// repaired bytes plus a boolean describing whether the result is valid
// JSON; anything unparseable is reported as not repairable.
func repairTruncatedJSON(data []byte) ([]byte, bool) {
	out := bytes.TrimRightFunc(data, func(r rune) bool {
		return r == ' ' || r == '\t' || r == '\r' || r == '\n'
	})
	if len(out) == 0 {
		return nil, false
	}

	// Already complete: nothing to repair.
	var v any
	if json.Unmarshal(out, &v) == nil {
		return out, true
	}

	// Remove a trailing comma or colon that cannot continue a document.
	for len(out) > 0 {
		last := out[len(out)-1]
		if last == ',' || last == ':' {
			out = bytes.TrimRight(out[:len(out)-1], " \t\r\n")
			continue
		}
		break
	}

	// Strip a trailing key or array element left dangling without its
	// value (e.g. '...,"content"' where the value was never written).
	// The regex only matches a quoted token sitting directly before the
	// end in key position, so complete values are preserved.
	keyTail := regexp.MustCompile(`[,{\[]\s*"(?:[^"\\]|\\.)*"\s*$`)
	for {
		stripped := keyTail.ReplaceAll(out, []byte(""))
		if bytes.Equal(stripped, out) {
			break
		}
		out = stripped
	}

	// Determine open string/bracket state.
	var closers []byte
	inString := false
	escaped := false
	for _, b := range out {
		switch {
		case inString:
			if escaped {
				escaped = false
				continue
			}
			if b == '\\' {
				escaped = true
				continue
			}
			if b == '"' {
				inString = false
			}
		default:
			switch b {
			case '"':
				inString = true
			case '{':
				closers = append(closers, '}')
			case '[':
				closers = append(closers, ']')
			case '}', ']':
				if n := len(closers); n > 0 && closers[n-1] == b {
					closers = closers[:n-1]
				}
			}
		}
	}

	if escaped {
		// A trailing backslash cannot be completed safely.
		return nil, false
	}
	closed := append([]byte(nil), out...)
	if inString {
		closed = append(closed, '"')
	}
	for i := len(closers) - 1; i >= 0; i-- {
		closed = append(closed, closers[i])
	}
	if json.Unmarshal(closed, &v) == nil {
		return closed, true
	}
	return nil, false
}

// List retrieves a list of all sessions from the .lato/sessions directory,
// returning an error if the directory cannot be read. Files that cannot
// be parsed are skipped rather than aborting the whole listing.
func List() ([]Session, error) {
	dir := filepath.Join(".", ".lato", "sessions")

	files, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return []Session{}, nil
	} else if err != nil {
		return nil, err
	}

	sessions := make([]Session, 0)

	for _, file := range files {
		if filepath.Ext(file.Name()) != ".json" || strings.HasSuffix(file.Name(), ".corrupt.bak") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(dir, file.Name()))
		if err != nil {
			continue
		}

		var s Session
		if err := json.Unmarshal(data, &s); err != nil {
			// Skip unreadable sessions; the user can still load valid ones.
			continue
		}

		sessions = append(sessions, s)
	}

	return sessions, nil
}
