#!/bin/bash
# Build script for Lato release binaries with Lato Free credential injection.
#
# Usage:
#   ./build_release.sh "sk-or-xxxxxxxxxxxx"
#
# The API key is injected into internal/providers/latofree_credential.go at build time.

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Usage: $0 <LATO_FREE_OPENROUTER_API_KEY>"
    exit 1
fi

LATO_FREE_KEY="$1"

# Validate key format (basic check)
if [[ ! "$LATO_FREE_KEY" =~ ^sk-or- ]]; then
    echo "Warning: Key doesn't look like an OpenRouter key (should start with sk-or-)"
fi

# Generate the credential file
CRED_FILE="internal/providers/latofree_credential.go"
cat > "$CRED_FILE" <<EOF
// Code generated by build script. DO NOT EDIT.
//
// This file contains the built-in Lato Free credential for release builds.
// The actual credential is injected at build time via the build script.

package providers

// LatoFreeBuiltinCredential is the built-in Lato Free OpenRouter API key.
// This value is injected at build time for release builds.
const LatoFreeBuiltinCredential = "$LATO_FREE_KEY"
EOF

echo "Generated $CRED_FILE with injected credential"